#!/bin/sh

set -e

lb config noauto \
   --clean \
   --memtest none \
   --distribution wheezy \
   --debian-installer live \
   --firmware-binary true \
   --firmware-chroot true \
   --apt-ftp-proxy 'http://localhost:3142/' \
   --apt-http-proxy 'http://localhost:3142/' \
   ${@}

